apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: org-mngmnt-ws-rb
  namespace: dev
subjects:
  - kind: ServiceAccount
    name: org-mngmnt-ws
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: org-mngmnt-ws-resource