apiVersion: v1
kind: Service
metadata:
  name: ws-organization-management
  namespace: dev
spec:
  selector:
    app: ws-organization-management-backend
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  sessionAffinity: None
  type: LoadBalancer
